### ISSUE TITLE
Values for L1, L2, and L3 are just listed as filter

### ISSUE THREAD

**Issue by washyu** [hkzlab/ES1868_ISA8#1]
In the schematic and on the silkscreen the value is just listed as Filter.  Could you please supply the value i really want to finish building this card but I am stuck because of this.

**Comment by hkzlab** [comment]
As shown on the schematics and in photo those are ferrite beads. Value is absolutely non critical, a simple jumper made with the leg of a resistor would probably work.
You can use these: https://www.mouser.it/ProductDetail/623-2743001112LF
